create table if not exists public.password_recovery_requests (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

comment on table public.password_recovery_requests is
  'Hashes e horários usados exclusivamente para limitar abuso da recuperação de senha.';

alter table public.password_recovery_requests enable row level security;

revoke all on table public.password_recovery_requests from anon, authenticated;
grant select, insert, delete on table public.password_recovery_requests to service_role;
grant usage, select on sequence public.password_recovery_requests_id_seq to service_role;

create index if not exists password_recovery_requests_email_created_idx
  on public.password_recovery_requests (email_hash, created_at desc);

create index if not exists password_recovery_requests_ip_created_idx
  on public.password_recovery_requests (ip_hash, created_at desc);
